# Generated by Django 3.2.22 on 2024-02-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='Bank',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='Bank',
            new_name='bank_name',
        ),
    ]
