# Generated by Django 3.2.22 on 2024-02-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240215_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='IFSC',
            new_name='ifsc',
        ),
    ]
